name: record_poc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  just_audio: ^0.10.4
  path: ^1.9.1
  path_provider: ^2.1.5
  record: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
